import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import type { ReconciliationRow, SalesOrder, CompanySettings } from '@/types'

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica' },
  header: { marginBottom: 20 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#666' },
  table: { marginTop: 10 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 4 },
  headerRow: { flexDirection: 'row', backgroundColor: '#f0fdf4', paddingVertical: 6, fontWeight: 'bold' },
  cell: { flex: 1, paddingHorizontal: 4 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#999', fontSize: 8 },
})

function formatNaira(amount: number) {
  return `₦${amount.toLocaleString('en-NG')}`
}

export function SalesDayReportPDF({
  company,
  date,
  rows,
  orders,
  generatedBy,
}: {
  company: CompanySettings
  date: string
  rows: ReconciliationRow[]
  orders: SalesOrder[]
  generatedBy: string
}) {
  const totalRevenue = orders.reduce((s, o) => s + o.total_amount, 0)
  const totalBirds = rows.reduce((s, r) => s + r.good_sold + r.second_class_sold, 0)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{company.company_name}</Text>
          <Text style={styles.subtitle}>Daily Sales Report — {date}</Text>
          <Text style={styles.subtitle}>Generated by {generatedBy}</Text>
        </View>

        <Text style={{ fontWeight: 'bold', marginBottom: 6 }}>Summary</Text>
        <Text>Total Revenue: {formatNaira(totalRevenue)}</Text>
        <Text>Total Birds Sold: {totalBirds}</Text>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.cell}>Bird Type</Text>
            <Text style={styles.cell}>Declared</Text>
            <Text style={styles.cell}>Good</Text>
            <Text style={styles.cell}>2nd</Text>
            <Text style={styles.cell}>Reject</Text>
            <Text style={styles.cell}>Mortality</Text>
            <Text style={styles.cell}>Transfer</Text>
            <Text style={styles.cell}>Balance</Text>
          </View>
          {rows.map((row) => (
            <View key={row.bird_type_id} style={styles.row}>
              <Text style={styles.cell}>{row.bird_type_name}</Text>
              <Text style={styles.cell}>{row.declared}</Text>
              <Text style={styles.cell}>{row.good_sold}</Text>
              <Text style={styles.cell}>{row.second_class_sold}</Text>
              <Text style={styles.cell}>{row.rejects}</Text>
              <Text style={styles.cell}>{row.mortality}</Text>
              <Text style={styles.cell}>{row.farm_transfer}</Text>
              <Text style={styles.cell}>{row.balance}</Text>
            </View>
          ))}
        </View>

        <Text style={{ fontWeight: 'bold', marginTop: 20, marginBottom: 6 }}>Orders</Text>
        {orders.map((o) => (
          <View key={o.id} style={styles.row}>
            <Text style={{ flex: 2 }}>{o.order_number} — {o.customer?.name}</Text>
            <Text style={styles.cell}>{formatNaira(o.total_amount)}</Text>
            <Text style={styles.cell}>{o.status}</Text>
          </View>
        ))}

        <Text style={styles.footer}>FlockDesk — Your Flock. Your Desk. Total Control.</Text>
      </Page>
    </Document>
  )
}

export async function downloadSalesDayPDF(props: Parameters<typeof SalesDayReportPDF>[0], filename: string) {
  const blob = await pdf(<SalesDayReportPDF {...props} />).toBlob()
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}