# FlockDesk Local Setup — Supabase + Docker Desktop
# Run from flockdesk folder: .\scripts\local-setup.ps1

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot\..

Write-Host "=== FlockDesk Local Setup ===" -ForegroundColor Green

# 1. Check Docker
Write-Host "`n[1/4] Checking Docker Desktop..." -ForegroundColor Cyan
docker info | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Docker Desktop is not running. Start Docker Desktop and retry." -ForegroundColor Red
    exit 1
}
Write-Host "Docker OK" -ForegroundColor Green

# 2. Init Supabase if needed
Write-Host "`n[2/4] Initializing Supabase..." -ForegroundColor Cyan
if (-not (Test-Path "supabase\config.toml")) {
    npx supabase init
}

# 3. Start Supabase local stack
Write-Host "`n[3/4] Starting Supabase (Docker)..." -ForegroundColor Cyan
npx supabase start

# 4. Apply migrations
Write-Host "`n[4/4] Applying database migrations..." -ForegroundColor Cyan
npx supabase db reset

# 5. Write .env.local
$status = npx supabase status -o env 2>&1 | Out-String
$apiUrl = if ($status -match 'API_URL="([^"]+)"') { $Matches[1] } else { "http://127.0.0.1:54321" }
$anonKey = if ($status -match 'ANON_KEY="([^"]+)"') { $Matches[1] } else { "" }

@"
# Auto-generated by local-setup.ps1
VITE_SUPABASE_URL=$apiUrl
VITE_SUPABASE_ANON_KEY=$anonKey
"@ | Set-Content ".env.local" -Encoding UTF8

Write-Host "`n=== Setup Complete ===" -ForegroundColor Green
Write-Host "Supabase Studio: http://127.0.0.1:54323" -ForegroundColor Yellow
Write-Host "API URL: $apiUrl" -ForegroundColor Yellow
Write-Host ".env.local created — restart dev server: npm run dev" -ForegroundColor Yellow
Write-Host "`nDemo users: create in Supabase Studio > Authentication, then link profiles table" -ForegroundColor Cyan